export const MAX_IMAGE_UPLOAD_MB = 60;
export const MAX_DOCUMENT_UPLOAD_MB = 60;

export const MAX_IMAGE_UPLOAD_BYTES = MAX_IMAGE_UPLOAD_MB * 1024 * 1024;
export const MAX_DOCUMENT_UPLOAD_BYTES = MAX_DOCUMENT_UPLOAD_MB * 1024 * 1024;
