"use server";

/**
 * Server-side helpers for team-channel message attachments (Phase 1.7 Wave C).
 *
 * Mirrors the Phase 1.2.5 thread-attachment pattern from
 * `src/lib/thread-attachments.ts` (key function: `uploadAttachment`) — we keep
 * the same mime→kind map and per-kind size caps so the UI can share the
 * validation shape. Unlike Phase 1.2.5 (which uploaded directly from the
 * browser via `supabase.storage.upload`), this subtask routes uploads through
 * *signed upload URLs* issued server-side so the bytes go straight to Supabase
 * Storage without bouncing through the Vercel Server Action (which has a 4 MB
 * request-body limit).
 *
 * Path convention (matches storage RLS on `team-channel-attachments`):
 *   {workspace_id}/{channel_id}/{message_id}/{uuid}__{filename}
 *
 * The `message_id` segment is a prospective UUID generated by the client BEFORE
 * the `team_channel_messages` row is inserted — all attachments for a send
 * share it. Safe because storage RLS only checks the first path segment.
 */

import { createSupabaseServer } from "@/lib/supabase/server";
import { createSupabaseService } from "@/lib/supabase/service";
import { isYagiInternalMember } from "@/lib/team-channels/queries";
import {
  BUCKET,
  attachmentSizeCaps,
  isAllowedMime,
  kindForMime,
  safeFileName,
  type AttachmentKind,
} from "@/lib/team-channels/attachment-caps";

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export type RequestUploadInputFile = {
  fileName: string;
  mimeType: string;
  size: number;
};

export type RequestUploadResultItem = {
  uploadUrl: string;
  token: string;
  storagePath: string;
  mimeType: string;
  size: number;
  fileName: string;
  kind: AttachmentKind;
};

export type RequestUploadResponse =
  | { ok: true; urls: RequestUploadResultItem[] }
  | {
      ok: false;
      error:
        | "auth_required"
        | "forbidden"
        | "validation"
        | "too_many"
        | "size"
        | "mime"
        | "channel_not_found"
        | "storage";
      index?: number;
    };

/**
 * Issues signed upload URLs (one per file) scoped to the new message.
 * Called from the client BEFORE the message row exists.
 */
export async function requestUploadUrls(input: {
  workspaceId: string;
  channelId: string;
  messageId: string;
  files: RequestUploadInputFile[];
}): Promise<RequestUploadResponse> {
  // basic shape validation
  if (
    !input ||
    typeof input.workspaceId !== "string" ||
    typeof input.channelId !== "string" ||
    typeof input.messageId !== "string" ||
    !Array.isArray(input.files)
  ) {
    return { ok: false, error: "validation" };
  }
  if (
    !UUID_RE.test(input.workspaceId) ||
    !UUID_RE.test(input.channelId) ||
    !UUID_RE.test(input.messageId)
  ) {
    return { ok: false, error: "validation" };
  }
  if (input.files.length === 0) return { ok: true, urls: [] };
  if (input.files.length > 5) return { ok: false, error: "too_many" };

  // auth: must be a YAGI Internal workspace member
  const supabase = await createSupabaseServer();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "auth_required" };
  const isMember = await isYagiInternalMember(supabase, user.id);
  if (!isMember) return { ok: false, error: "forbidden" };

  // channel must exist + belong to workspace
  const { data: channel, error: chErr } = await supabase
    .from("team_channels")
    .select("id, workspace_id")
    .eq("id", input.channelId)
    .maybeSingle();
  if (chErr || !channel) return { ok: false, error: "channel_not_found" };
  if (channel.workspace_id !== input.workspaceId) {
    return { ok: false, error: "validation" };
  }

  // per-file validation + storage-path construction
  type Prepared = RequestUploadResultItem & { storagePath: string };
  const prepared: Prepared[] = [];
  for (let i = 0; i < input.files.length; i++) {
    const f = input.files[i];
    if (
      !f ||
      typeof f.fileName !== "string" ||
      typeof f.mimeType !== "string" ||
      typeof f.size !== "number" ||
      f.size < 0
    ) {
      return { ok: false, error: "validation", index: i };
    }
    if (!isAllowedMime(f.mimeType)) {
      return { ok: false, error: "mime", index: i };
    }
    const kind = kindForMime(f.mimeType);
    if (f.size > attachmentSizeCaps[kind]) {
      return { ok: false, error: "size", index: i };
    }
    const uuid = crypto.randomUUID();
    const cleanName = safeFileName(f.fileName);
    const storagePath = `${input.workspaceId}/${input.channelId}/${input.messageId}/${uuid}__${cleanName}`;

    prepared.push({
      uploadUrl: "",
      token: "",
      storagePath,
      mimeType: f.mimeType,
      size: f.size,
      fileName: cleanName,
      kind,
    });
  }

  // Issue signed upload URLs via service role. We don't create a new
  // service-role wrapper — we reuse `createSupabaseService` from
  // `src/lib/supabase/service.ts`.
  const admin = createSupabaseService();
  for (const item of prepared) {
    const { data, error } = await admin.storage
      .from(BUCKET)
      .createSignedUploadUrl(item.storagePath);
    if (error || !data) {
      return { ok: false, error: "storage" };
    }
    item.uploadUrl = data.signedUrl;
    item.token = data.token;
  }

  return {
    ok: true,
    urls: prepared.map((p) => ({
      uploadUrl: p.uploadUrl,
      token: p.token,
      storagePath: p.storagePath,
      mimeType: p.mimeType,
      size: p.size,
      fileName: p.fileName,
      kind: p.kind,
    })),
  };
}
